# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: "aws-runner"
    cloud: "aws"
    region: "us-west-2"
    instance_type: "m7a.2xlarge"
    # Ubuntu-24.04, 64GB, us-west-2
    machine_image: "ami-04c4dd2e810da6cfe"
    preemptible: false
    labels:
      - "cirun-aws-amd64"
