name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build rootfs
        run: sudo ./rootfs.sh
      - name: upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-alpine
          path: output/rootfs-alpine.tar.gz
  build-system:
    runs-on: ubuntu-latest
    needs: build-rootfs
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: download rootfs
        uses: actions/download-artifact@v4
        with:
          name: rootfs-alpine
      - name: build system
        run: ./system.sh
      - name: upload update.img
        uses: actions/upload-artifact@v4
        with:
          name: update-img
          path: output/update.img
