name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build rootfs
        run: ./rootfs.sh
      - name: print
        run: ls
      - name: upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-alpine
          path: output/rootfs-alpine.tar.gz
