name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build rootfs
        run: sudo ./rootfs.sh
      - name: rename rootfs file
        run: sudo mv output/rootfs-alpine.tar.gz output/rootfs-alpine
      - name: upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: output/rootfs-alpine
